#
# Copyright (c) 2023-2024 NVIDIA CORPORATION AND AFFILIATES.  All rights reserved.
#
# GitLab CI/CD pipeline for building XenoFlow with DOCA Flow on Ubuntu
#

stages:
  - build

variables:
  # Meson build directory
  BUILD_DIR: "builddir"
  # DOCA installation path
  DOCA_PATH: "/opt/mellanox/doca"

build:ubuntu:
  stage: build
  image: ubuntu:22.04
  
  before_script:
    # Update package lists and install basic build tools
    - apt-get update -y
    - apt-get install -y wget gnupg software-properties-common ca-certificates
    
    # Install build dependencies
    - apt-get install -y 
        build-essential 
        pkg-config 
        python3 
        python3-pip 
        ninja-build 
        meson
        libcjson-dev
        git
    
    # Install DOCA SDK from apt repository
    # Note: This requires the NVIDIA DOCA repository to be accessible
    # For actual DOCA development, you would need a runner with NVIDIA BlueField DPU
    - wget https://linux.mellanox.com/public/repo/doca/2.9.1/ubuntu22.04/x86_64/doca-repo.deb
    - dpkg -i doca-repo.deb
    - apt-get update
    - apt-get install -y doca-all doca-tools
    
    # Display environment information
    - echo "Build environment:"
    - meson --version
    - python3 --version
    - gcc --version
    
  script:
    # Verify DOCA installation
    - |
      if [ -d "$DOCA_PATH" ]; then
        echo "DOCA SDK successfully installed at $DOCA_PATH"
      else
        echo "WARNING: DOCA SDK not found at $DOCA_PATH after installation"
        echo "Installation may have failed. Checking package status..."
        dpkg -l | grep doca || true
        exit 1
      fi
    
    # Configure the build with Meson
    - meson setup $BUILD_DIR
    
    # Compile the project
    - meson compile -C $BUILD_DIR
    
    # Display build results
    - ls -lh $BUILD_DIR/
    - echo "Build completed successfully!"
    
  artifacts:
    name: "xeno_flow-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - builddir/xeno_flow
      - builddir/compile_commands.json
    expire_in: 1 week
    when: on_success
  
  tags:
    # This job installs DOCA SDK from apt repository during build
    # Adjust the tag based on your GitLab runner configuration
    - ubuntu
  
  rules:
    # Run on all branches
    - if: $CI_PIPELINE_SOURCE == "push"
    # Run on merge requests
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Run on tags
    - if: $CI_COMMIT_TAG

# Optional: Add a test stage if you have tests
# test:ubuntu:
#   stage: test
#   image: ubuntu:22.04
#   dependencies:
#     - build:ubuntu
#   script:
#     - ./builddir/xeno_flow --help
#   tags:
#     - ubuntu
